require('packer-config')
require('settings')
require('mappings')
-- require('colorschemes-config.nightfox')
require('colorschemes-config.catppuccin')
require('nvim-tree-config')
require('lsp-config.language-servers')
require('lsp-config.nvim-cmp')
require('lsp-config.null-ls')
require('lualine-config')
require('barbar-config')
require('nvim-treesitter-config')

